---
- hosts: all
  tasks:
  -name: Install mysql_db
  ansible install name= mysql-common status='present' status='running'
  
  -name: Install PHP
  ansible install name= php  status='present'
  
  -name: Install WordPress
  ansible install name= wordpress-l10n status='present'
